import Navbar from '@/components/Navbar';
import Form from '@/components/Form';
import Head from 'next/head';
import React from 'react';

const form = () => {

  return (
    <>
    <Head>
        <title>SS Generate Collection NFT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
        <Navbar />
        <Form  />
    </main>
    </>
  )
}

export default form